package dev.ynagai.firebase.ai

/**
 * Represents content that can be sent to or received from a generative AI model.
 *
 * Content consists of a role (e.g., "user" or "model") and a list of [Part]s
 * that make up the message body.
 *
 * @property role The role of the content creator. Typically "user" for user messages
 *                or "model" for AI responses.
 * @property parts The list of content parts (text, images, etc.).
 *
 * @see content DSL function for building Content instances
 */
data class Content(
    val role: String? = null,
    val parts: List<Part> = emptyList(),
)

/**
 * A part of [Content] that can be sent to or received from a model.
 *
 * Implementations include:
 * - [TextPart]: Plain text content
 * - [InlineDataPart]: Binary data like images, audio, and video
 *
 * @see TextPart
 * @see InlineDataPart
 */
sealed interface Part

/**
 * A text part of content.
 *
 * @property text The text content.
 * @property isThought Whether this text is part of the model's thinking process (Gemini thinking).
 */
data class TextPart(
    val text: String,
    val isThought: Boolean = false,
) : Part

/**
 * An inline binary data part of content, used for images, audio, and video.
 *
 * @property mimeType The MIME type of the data (e.g., "image/png", "audio/mpeg", "video/mp4").
 * @property data The raw binary data.
 * @property displayName An optional human-readable name for the data. Only populated on Android;
 *                       always null on iOS, which does not expose it.
 * @property isThought Whether this part is part of the model's thinking process (Gemini thinking).
 *                     Response-only; ignored when sending content to the model.
 *
 * @sample
 * ```kotlin
 * val imagePart = InlineDataPart(
 *     mimeType = "image/png",
 *     data = imageByteArray
 * )
 * ```
 */
data class InlineDataPart(
    val mimeType: String,
    val data: ByteArray,
    val displayName: String? = null,
    val isThought: Boolean = false,
) : Part {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false
        other as InlineDataPart
        if (mimeType != other.mimeType) return false
        if (!data.contentEquals(other.data)) return false
        if (displayName != other.displayName) return false
        if (isThought != other.isThought) return false
        return true
    }

    override fun hashCode(): Int {
        var result = mimeType.hashCode()
        result = 31 * result + data.contentHashCode()
        result = 31 * result + (displayName?.hashCode() ?: 0)
        result = 31 * result + isThought.hashCode()
        return result
    }
}

/**
 * A file data part referencing a file by URI.
 *
 * @property mimeType The MIME type of the file (e.g., "image/png", "application/pdf").
 * @property uri The URI of the file.
 * @property isThought Whether this part is part of the model's thinking process (Gemini thinking).
 *                     Response-only; ignored when sending content to the model.
 */
data class FileDataPart(
    val mimeType: String,
    val uri: String,
    val isThought: Boolean = false,
) : Part

/**
 * A function call part generated by the model.
 *
 * @property name The name of the function to call.
 * @property args The arguments to pass to the function.
 * @property id Unique identifier of this function call. Used by the model to correlate
 *             a [FunctionResponsePart] back to the originating call — essential for parallel
 *             calls to the same function. May be null when the backend does not provide one.
 * @property isThought Whether this part is part of the model's thinking process (Gemini thinking).
 *                     Response-only; ignored when sending content to the model.
 */
data class FunctionCallPart(
    val name: String,
    val args: Map<String, Any?> = emptyMap(),
    val id: String? = null,
    val isThought: Boolean = false,
) : Part

/**
 * A function response part providing the result of a function call.
 *
 * @property name The name of the function that was called.
 * @property response The response data from the function.
 * @property id The id of the [FunctionCallPart] this responds to. Forward the call's id here
 *             so the model can correlate the response to the right call.
 * @property isThought Whether this part is part of the model's thinking process (Gemini thinking).
 *                     Response-only; ignored when sending content to the model.
 */
data class FunctionResponsePart(
    val name: String,
    val response: Map<String, Any?> = emptyMap(),
    val id: String? = null,
    val isThought: Boolean = false,
) : Part

/**
 * A part containing executable code generated by the model.
 *
 * @property language The programming language of the code.
 * @property code The source code string.
 * @property isThought Whether this part is part of the model's thinking process (Gemini thinking).
 *                     Response-only; ignored when sending content to the model.
 */
data class ExecutableCodePart(
    val language: String,
    val code: String,
    val isThought: Boolean = false,
) : Part

/**
 * Outcome of code execution.
 */
enum class CodeExecutionOutcome {
    OK,
    FAILED,
    DEADLINE_EXCEEDED,
    UNSPECIFIED,
}

/**
 * A part containing the result of code execution.
 *
 * @property outcome The outcome of the code execution.
 * @property output The output produced by the code execution.
 * @property isThought Whether this part is part of the model's thinking process (Gemini thinking).
 *                     Response-only; ignored when sending content to the model.
 */
data class CodeExecutionResultPart(
    val outcome: CodeExecutionOutcome,
    val output: String = "",
    val isThought: Boolean = false,
) : Part
