package dev.ynagai.firebase.ai

/**
 * A message received from the server during a live session.
 *
 * This sealed interface represents the different types of messages that can be
 * received from the server during a real-time streaming session.
 */
sealed interface LiveServerMessage {

    /**
     * A content message from the server.
     *
     * @property content The content generated by the model, or null if no content.
     * @property isTurnComplete Whether the model has finished its current turn.
     * @property wasInterrupted Whether the model's response was interrupted.
     * @property isGenerationComplete Whether the model has finished generating its response for
     *                                this turn (distinct from [isTurnComplete], which also accounts
     *                                for tool execution).
     * @property inputTranscription Transcription text of the user's input audio, if available.
     * @property outputTranscription Transcription text of the model's output audio, if available.
     */
    data class Content(
        val content: dev.ynagai.firebase.ai.Content?,
        val isTurnComplete: Boolean = false,
        val wasInterrupted: Boolean = false,
        val isGenerationComplete: Boolean = false,
        val inputTranscription: String? = null,
        val outputTranscription: String? = null,
    ) : LiveServerMessage

    /**
     * A tool call message from the server, requesting function execution.
     *
     * @property functionCalls The list of function calls to execute.
     */
    data class ToolCall(
        val functionCalls: List<FunctionCallPart>,
    ) : LiveServerMessage

    /**
     * A notification that previously requested tool calls have been cancelled.
     *
     * @property ids The IDs of the cancelled tool calls.
     */
    data class ToolCallCancellation(
        val ids: List<String>,
    ) : LiveServerMessage

    /**
     * A notification that the server is about to disconnect.
     */
    data object GoingAway : LiveServerMessage

    /**
     * An update of the session resumption state.
     *
     * Only sent if [SessionResumptionConfig] was set in the session setup.
     *
     * @property newHandle The new handle that represents the resumable state.
     * @property resumable Whether the session can be resumed at this point.
     */
    data class SessionResumptionUpdate(
        val newHandle: String? = null,
        val resumable: Boolean? = null,
    ) : LiveServerMessage
}
