package dev.ynagai.firebase.ai

/**
 * A message received from the server during a live session.
 *
 * This sealed interface represents the different types of messages that can be
 * received from the server during a real-time streaming session.
 */
sealed interface LiveServerMessage {

    /**
     * A content message from the server.
     *
     * @property content The content generated by the model, or null if no content.
     * @property isTurnComplete Whether the model has finished its current turn.
     * @property wasInterrupted Whether the model's response was interrupted.
     */
    data class Content(
        val content: dev.ynagai.firebase.ai.Content?,
        val isTurnComplete: Boolean = false,
        val wasInterrupted: Boolean = false,
    ) : LiveServerMessage

    /**
     * A tool call message from the server, requesting function execution.
     *
     * @property functionCalls The list of function calls to execute.
     */
    data class ToolCall(
        val functionCalls: List<FunctionCallPart>,
    ) : LiveServerMessage

    /**
     * A notification that previously requested tool calls have been cancelled.
     *
     * @property ids The IDs of the cancelled tool calls.
     */
    data class ToolCallCancellation(
        val ids: List<String>,
    ) : LiveServerMessage

    /**
     * A notification that the server is about to disconnect.
     */
    data object GoingAway : LiveServerMessage
}
