[versions]
agp = "9.2.1"
android-compileSdk = "36"
android-minSdk = "24"
firebase-apple = "12.14.0"
firebase-bom = "34.14.0"
firebase-objc = "0.5.0"
gms-ads-identifier = "18.2.0"
kotlin = "2.4.0"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"
publish = "0.36.0"
androidx-test-core = "1.7.0"
androidx-test-runner = "1.7.0"

[libraries]
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-android-ai = { module = "com.google.firebase:firebase-ai" }
firebase-android-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-android-common = { module = "com.google.firebase:firebase-common" }
firebase-android-auth = { module = "com.google.firebase:firebase-auth" }
firebase-android-firestore = { module = "com.google.firebase:firebase-firestore" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "gms-ads-identifier" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
